name: Add Label to Issue
description: Add Label to repository
inputs:
  USER_PAT:
    description: 'Enter the Personal Access Token'
    required: true
  ORG_NAME:
    description: 'Organization name'
    required: true  
  REPO_NAME:
    description: 'Repository name'
    required: true   
  LABELS:
    description: 'Label name'
    required: true  
  ISSUE_NUMBER:
    description: 'Issue number'
    required: true
  
outputs:
  ASSIGN_LABEL_RESPONSE:
    description: 'Response from GitHub API'
    value: ${{ steps.add-label-to-Issue.response }}

runs:
  using: composite
  steps:   

    - name: Add Label to Issue
      id: add-label-to-Issue
      env:
        GITHUB_TOKEN: ${{ inputs.USER_PAT }}
      run: |
        echo "LABELS=${{ inputs.LABELS }}"
        labels=$(echo '${{ inputs.LABELS }}' | tr ',' '\n' | jq -R . | jq -s .)
        response=$(curl -L \
              -X POST \
              -H "Accept: application/vnd.github+json" \
              -H "Authorization: token ${{ inputs.USER_PAT }}" \
              -H "X-GitHub-Api-Version: 2022-11-28" \
              https://api.github.com/repos/${{ inputs.ORG_NAME }}/${{ inputs.REPO_NAME }}/issues/${{ inputs.ISSUE_NUMBER }}/labels \
              -d "{\"labels\":$labels}")
        echo "::set-output name=response::$response"
      shell: bash        
