name: Create Repo - Assign
on:
  issues:
    types:
      - opened
env:
  LGTM_TEAM: lgtm-reviewers
jobs:
  assign:
    name: Assign new issue
    runs-on: ubuntu-20.04
    if: contains(github.event.issue.labels.*.name, 'createrepo') && github.event.action == 'opened'
    steps:
      - name: Assign
        uses: andyfeller/issueops-createrepo/assign@v1
        with:
          authentication: app
          application-id: ${{ secrets.APP_ID }}
          application-private-key: ${{ secrets.APP_PEM }}
          team-assign: ${{ env.LGTM_TEAM }}
