name: Add User to Team
description: Add User to Team

inputs:
  ORG:
    description: 'Enter organization name'
    required: true
    default: ${{ github.repository_owner }}
  TEAM_SLUG:
    description: 'Enter name of the Team'
    required: true
  USERNAME:
    description: 'Enter handle name of user'
    required: true
  ROLE:
    description: 'Enter role of user'
    required: true
  USER_TOKEN:
    description: 'Enter Personal access token of user'
    required: true      
  HOSTNAME:
    description: 'Enter the hostname'
    required: true 

runs:
  using: composite 
  steps:
      - name: Authenticate with GitHub
        run: |
          echo "${{ inputs.USER_TOKEN }}" | gh auth login -h "${{ inputs.HOSTNAME }}" --with-token
        shell: bash  

      - name: Add users to organization
        run: |
          gh api \
          --method PUT \
          -H "Accept: application/vnd.github+json" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          --hostname "${{ inputs.HOSTNAME }}" \
          "/orgs/${{ inputs.ORG }}/teams/${{ inputs.TEAM_SLUG }}/memberships/${{ inputs.USERNAME }}" \
          -f "role=${{ inputs.ROLE }}"
        shell: bash  