name: Update the logs to README.md file
description: Update the README.md file with the latest logs
inputs:
  USER_PAT:
    description: Enter the USER_PAT
    required: true
  ORG_NAME:
    description: Enter the ORG_NAME
    required: true
  BRANCH_NAME:
    description: Enter the BRANCH_NAME
    required: true      
  REQUESTOR:
    description: Enter Requestor name
    required: true    
  CREATED_AT:
    description: Enter the CREATED_AT date
    required: true
  ISSUE_URL:
    description: Enter the ISSUE_URL
    required: true
  ISSUE_ASSIGNEES:
    description: Enter the ASSIGNEES
    required: true
  ISSUE_JSON:
    description: Enter the ISSUE_JSON
    required: true   
  CREATE_MODIFY:
    description: Enter the CREATE_MODIFY
    required: true  

runs:
  using: composite
  steps:
    
    - name: Checkout the repository      
      run: |
        git checkout ${{ inputs.BRANCH_NAME }}  
    
        #Check if the file exists in the destination directory
        readme_file=$GITHUB_WORKSPACE/provisioner/settings/${{ inputs.ORG_NAME }}/${{ inputs.ORG_NAME }}.md
        if [ ! -f $readme_file ]; then
          echo "File does not exists in root directory"
          #Create the README.md file and add the table headers
          echo "| Requestor | Date | Issue URL | Issue Assignees | Issue JSON | New or Update |" >> $readme_file
          echo "| --- | --- | --- | --- | --- | --- |" >> $readme_file
        fi
          echo "File exist in root directory"
          echo "| ${{ inputs.REQUESTOR }} | ${{ inputs.CREATED_AT }} | ${{ inputs.ISSUE_URL }} | ${{ inputs.ISSUE_ASSIGNEES }} | ${{ env.ISSUE_JSON }} | ${{ inputs.CREATE_MODIFY }} | " >> $readme_file
      env:
       ISSUE_JSON: ${{ inputs.ISSUE_JSON }} 
       GITHUB_TOKEN: ${{ inputs.USER_PAT }}
      shell: bash 
