name: Append include/exclude json
description: 'Append enforce section in the include/exclude json file'

inputs:
  ORG_NAME:
    description: 'Name of the Organization'
    required: true
  REPO_NAME:
    description: 'Name of the Repo'
    required: true 
  INCLUDE_EXCLUDE_FILE_NAME:
    description: 'Name of the include/exclude file'
    required: true  

outputs:
  RESPONSE:
    description: 'Status of the Organization and Repo'
    value: ${{ steps.append-enforce-section.outputs.response }}  

runs:
  using: composite
  steps:
    - name: append enforce section
      id: append-enforce-section
      run: |
          json_file="./provisioner/settings/include-exclude.json"         
          # make an entry for organization and repo in the json file
          jq ".enforce.\"${{ inputs.ORG_NAME }}\" += [\"${{ inputs.REPO_NAME }}\"]" ${{ inputs.INCLUDE_EXCLUDE_FILE_NAME }} > temp.json && mv temp.json ${{ inputs.INCLUDE_EXCLUDE_FILE_NAME }}
          if [ $? -eq 0 ]; then
            echo "::set-output name=response::Success"
          else
            echo "::set-output name=response::Failure"
          fi
      shell: bash
