name: test-get-all-labels-issue

on:
  workflow_dispatch:
    inputs:
      ORG_NAME:
        description: 'Organization name'
        required: true  
      REPO_NAME:
        description: 'Repository name'
        required: true   
      ISSUE_NUMBER:
        description: 'Issue Number'
        required: true
jobs:
  get-all-labels-issue:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
