name: test-enforce-repo-settings

on:
  workflow_dispatch:
    inputs:
      ORG_NAME:
        description: 'Organization Name'
        required: true
jobs:
  enforce-repo-settings:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
