name: Run bat file

on: [push]

jobs:
  run-bat:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Run bat file
      run: |
        cd $GITHUB_WORKSPACE/provisioner/tests/
        chmod +x test-add-assignee-to-issue.bat.
        test-add-assignee-to-issue.bat
