name: test-get-all-labels-issue

on:
  workflow_dispatch:
    inputs:
      ORG_NAME:
        description: 'Organization name'
        required: true  
      REPO_NAME:
        description: 'Repository name'
        required: true   
      ISSUE_NUMBER:
        description: 'Issue Number'
        required: true
jobs:
  get-all-labels-issue:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install gh CLI
        run: |
          sudo apt-get update
          sudo apt-get install gh 

      - name: Login to GitHub
        run: |
          gh auth login --with-token <<< "${{ secrets.ISSUE_OPS_TOKEN }}" 

      - name: Get all labels of an issue
        id: get-all-labels-issue
        uses: ./provisioner/actions/get-all-labels-issue
        with:
          USER_PAT: ${{ secrets.ISSUE_OPS_TOKEN }}
          ORG_NAME: ${{ github.event.inputs.ORG_NAME }}
          REPO_NAME: ${{ github.event.inputs.REPO_NAME }}
          ISSUE_NUMBER: ${{ github.event.inputs.ISSUE_NUMBER }}

      - name: Print all labels of an issue
        run: |
          echo "${{ steps.get-all-labels-issue.outputs.LABEL_RESPONSE }}"
