name: test-authenticate

on:
  workflow_dispatch:
    inputs:
      org_name:
        description: 'Organization Name'
        required: true
jobs:
  authenticate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
