name: test-add-topic-to-repo

on:
  workflow_dispatch:
    inputs:
      ORG_NAME:
        description: 'Organization Name'
        required: true
      REPO_NAME:
        description: 'Repository Name'
        required: true
      TOPICS:
        description: 'Topics'
        required: true
jobs:
  Add-topics-repo:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Add topics to repository
        uses: ./provisioner/actions/add-update-topics-to-repo
        with:
          USER_PAT: ${{ secrets.ISSUE_OPS_TOKEN }}
          ORG_NAME: ${{ github.event.inputs.ORG_NAME }}
          REPO_NAME: ${{ github.event.inputs.REPO_NAME }}
          TOPICS: ${{ github.event.inputs.TOPICS }}